#!/usr/bin/env bash
# Display content of /etc/passwd
while IFS=: read -r username _ userid _ _ home _; do
echo "Username: $username"
echo "User ID: $userid"
echo "Home Directory: $home"
echo "-------------------"
done < /etc/passwd
