#!/usr/bin/env bash
# Display story based on /etc/passwd
while IFS=: read -r username _ userid groupid _ home shell; do
echo "The user $username is part of the $groupid gang,"
echo "lives in $home and rides $shell."
echo "User $userid's place is protected by the passcode PASSWORD,"
echo "more info about the user here: USER $userid INFO"
echo "----------------------------------------------"
done < /etc/passwd
