#!/usr/bin/env bash
# Loop from 1 to 20 with different messages based on iteration
count=1
while ((count <= 20)); do
case $count in
4)
echo "4"
echo "bad luck from china"
;;
9)
echo "9"
echo "bad luck from japan"
;;
17)
echo "17"
echo "bad luck from italy"
;;
*)
echo $count
;;
esac
((count++))
done
