#!/usr/bin/env bash
# Display content of current directory
for item in *; do
if [[ -f $item || -d $item ]] && [[ $item != .* ]]; then
name="${item#*-}"  # Extract part after first dash
echo "$name"
fi
done
